# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-28 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('place', models.CharField(max_length=64)),
                ('url', models.CharField(blank=True, max_length=25)),
                ('description', models.CharField(max_length=1024)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('incharge', models.CharField(blank=True, max_length=256)),
                ('achievement', models.CharField(blank=True, max_length=256)),
                ('keyword', models.CharField(blank=True, max_length=256)),
                ('url', models.CharField(blank=True, max_length=256)),
                ('description', models.CharField(max_length=1024)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JobeRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('description', models.CharField(max_length=1024)),
                ('order', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takayoshi.Company')),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takayoshi.JobeRole'),
        ),
    ]
